HelloDocteur/src/Entity/Had.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\HadRepository")
 */
class Had
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Adresse;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $Tel;
    /**
    * @ORM\Column(type="string", length=250)
    */
   private $motif;

    
     /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Patient")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Patient;
 /**
     * @ORM\Column(type="boolean")
     */
    private $etat;

    /**
     * @ORM\Column(type="datetime")
     */
    private $datedemande;
     
    public function getId()
    {
        return $this->id;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->Tel;
    }

    public function setTel(string $Tel): self
    {
        $this->Tel = $Tel;

        return $this;
    }

    public function getFichemaladie()
    {
        return $this->Fichemaladie;
    }

    public function setFichemaladie($Fichemaladie): self
    {
        $this->Fichemaladie = $Fichemaladie;

        return $this;
    }

    /**
     * Get the value of Patient
     */ 
    public function getPatient()
    {
        return $this->Patient;
    }

    /**
     * Set the value of Patient
     *
     * @return  self
     */ 
    public function setPatient($Patient)
    {
        $this->Patient = $Patient;

        return $this;
    }

   /**
    * Get the value of motif
    */ 
   public function getMotif()
   {
      return $this->motif;
   }

   /**
    * Set the value of motif
    *
    * @return  self
    */ 
   public function setMotif($motif)
   {
      $this->motif = $motif;

      return $this;
   }

    /**
     * Get the value of etat
     */ 
    public function getEtat()
    {
        return $this->etat;
    }

    /**
     * Set the value of etat
     *
     * @return  self
     */ 
    public function setEtat($etat)
    {
        $this->etat = $etat;

        return $this;
    }

    public function getDatedemande(): ?\DateTimeInterface
    {
        return $this->datedemande;
    }

    public function setDatedemande(\DateTimeInterface $datedemande): self
    {
        $this->datedemande = $datedemande;

        return $this;
    }
}

HelloDocteur/src/Entity/Medecin.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
/**
 * @ORM\Entity(repositoryClass="App\Repository\MedecinRepository")
 */
class Medecin
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $Matricule;

   /**
     * @ORM\Column(type="string", length=90, unique=false)
     * @Assert\NotBlank()
     */
    private $nomcomplet;
    
    /**
     * @ORM\Column(type="string", length=30)
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $Tel;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $Adresse;

    /**
     * @ORM\Column(type="float",nullable=true)
     */
    private $Latitude;

    /**
     * @ORM\Column(type="float",nullable=true)
     */
    private $Longitude;
     /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Quartier")
     * @ORM\JoinColumn(nullable=true)
     */
    private $Quartier;
     /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Specialite")
     * @ORM\JoinColumn(nullable=true)
     */
    private $Specialite;


     /**
     * @ORM\OneToMany(targetEntity="App\Entity\Structure",mappedBy="medecins")
     * @ORM\JoinColumn(nullable=true)
     */
    private $structure;
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Creneau",mappedBy="medecin")
     * @ORM\JoinColumn(nullable=true)
     */
    private $creneau;
    /**
     * 
     * @ORM\Column(type="blob",nullable=true)
     */

    private $image;

    public function getId()
    {
        return $this->id;
    }

    public function getMatricule(): ?string
    {
        return $this->Matricule;
    }

    public function setMatricule(string $Matricule): self
    {
        $this->Matricule = $Matricule;

        return $this;
    }

  

    
    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->Tel;
    }

    public function setTel(string $Tel): self
    {
        $this->Tel = $Tel;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->Latitude;
    }

    public function setLatitude(float $Latitude): self
    {
        $this->Latitude = $Latitude;

        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->Longitude;
    }

    public function setLongitude(float $Longitude): self
    {
        $this->Longitude = $Longitude;

        return $this;
    }

    /**
     * Get the value of Quartier
     */ 
    public function getQuartier()
    {
        return $this->Quartier;
    }

    /**
     * Set the value of Quartier
     *
     * @return  self
     */ 
    public function setQuartier($Quartier)
    {
        $this->Quartier = $Quartier;

        return $this;
    }

    /**
     * Get the value of Specialite
     */ 
    public function getSpecialite()
    {
        return $this->Specialite;
    }

    /**
     * Set the value of Specialite
     *
     * @return  self
     */ 
    public function setSpecialite($Specialite)
    {
        $this->Specialite = $Specialite;

        return $this;
    }

    
    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image): self
    {
        $this->image = $image;

        return $this;
    }

    

    /**
     * Get the value of structure
     */ 
    public function getStructure()
    {
        return $this->structure;
    }

    /**
     * Set the value of structure
     *
     * @return  self
     */ 
    public function setStructure($structure)
    {
        $this->structure = $structure;

        return $this;
    }

    /**
     * Get the value of nomcomplet
     */ 
    public function getNomcomplet()
    {
        return $this->nomcomplet;
    }

    /**
     * Set the value of nomcomplet
     *
     * @return  self
     */ 
    public function setNomcomplet($nomcomplet)
    {
        $this->nomcomplet = $nomcomplet;

        return $this;
    }


    /**
     * Get the value of creneau
     */ 
    public function getCreneau()
    {
        return $this->creneau;
    }

    /**
     * Set the value of creneau
     *
     * @return  self
     */ 
    public function setCreneau($creneau)
    {
        $this->creneau = $creneau;

        return $this;
    }
}

HelloDocteur/src/Form/MedecinType.php
<?php

namespace App\Form;

use App\Entity\Medecin;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MedecinType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Matricule',TextType::class)
            ->add('nomcomplet',TextType::class)
            ->add('Email',TextType::class)
            ->add('Tel',NumberType::class)
            ->add('Adresse',TextType::class)
            ->add('Latitude',NumberType::class)
            ->add('Longitude',NumberType::class)
            ->add('image',BlobType::class)
            ->add('Quartier',Quartier::class)
            ->add('Specialite',Specialite::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Medecin::class,
        ]);
    }
}

HelloDocteur/src/Controller/MedecinController.php
<?php

namespace App\Controller;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use App\Repository\MedecinRepository;
use App\Repository\CreneauRepository;
use App\Repository\PriseDeRendezvousRepository;
use App\Repository\CreneauItemRepository;
use App\Entity\Creneau;
use App\Entity\Medecin;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\HttpFoundation\Response;


class MedecinController extends Controller
{
    /**
     * @Route("/medecin", name="medecin")
     */
    public function index(MedecinRepository $medecinrepo)
    {
        $usermedecin= $this->getUser();
        $emailmedecin=$usermedecin->getEmail();
        $medecinloggedIn=$medecinrepo->findBy(['Email'=>$emailmedecin]);
        $medecinloggedIn[0]->setImage(base64_encode(stream_get_contents($medecinloggedIn[0]->getImage())));

        return $this->render('medecin/index.html.twig', [
            'controller_name' => 'MedecinController','medecinloggedIn'=>$medecinloggedIn
        ]);
    }
    /**
     * @Route("/ListeCReneau", name="ListeCReneau")
     */
    public function getAllCreneau(MedecinRepository $medecinrepo,CreneauRepository $creneaurepo,Request $request) {
        $usermedecin= $this->getUser();
        $emailmedecin=$usermedecin->getEmail();
        $medecinloggedIn=$medecinrepo->findBy(['Email'=>$emailmedecin]);
        $idmedecin=$medecinloggedIn[0]->getId();

        $listecreneau=$creneaurepo->findBy(['medecin'=>$idmedecin]);
        
        return $this->render('medecin/listecreneau.html.twig', [
            'creneau'=>$listecreneau,
            'medecinloggedIn'=>$medecinloggedIn
        ]);
    }
    /**
     * @Route("/AddCreneau", name="AddCreneau")
     */
    public function AddCreneau(MedecinRepository $medecinrepo,CreneauItemRepository $creneauitemrepo,CreneauRepository $creneaurepo,Request $request) {
        $usermedecin= $this->getUser();
        $emailmedecin=$usermedecin->getEmail();
        $medecinloggedIn=$medecinrepo->findBy(['Email'=>$emailmedecin]);
        $idmedecin=$medecinloggedIn[0]->getId();
        $listecreneauitem=$creneauitemrepo->findAll();
    if(isset($_POST['AJouter'])){
            if($request->isMethod('POST')){
                extract($_POST);
        $lecreneauitem=$creneauitemrepo->findOneBy(['id'=>$un]);

        $creneau= new Creneau();
        $creneau->setHeuredebut($heuredebut);
        $creneau->setHeurefin($heurefin);
        $creneau->setEtat(false);
        $creneau->setMedecin($medecinloggedIn[0]);
        $creneau->setCreneauitem($lecreneauitem);
        $em=$this->getDoctrine()->getManager();
        $em->persist($creneau);
        $em->flush();
        $this->addFlash('info', 'Ajouté avec succes.');
        return $this->redirectToRoute('ListeCReneau');
       
            }
    }
        return $this->render('medecin/addcreneau.html.twig', [
            'medecinloggedIn'=>$medecinloggedIn,
            'listecreneauitem'=>$listecreneauitem
        ]);
    }
 /**
     * @Route("/creneauedit/{id}", name="creneauedit")
    */
    public function creneauedit($id,MedecinRepository $medecinrepo,CreneauItemRepository $creneauitemrepo,CreneauRepository $creneaurepo,Request $request)
    {
        $usermedecin= $this->getUser();
        $emailmedecin=$usermedecin->getEmail();
        $medecinloggedIn=$medecinrepo->findBy(['Email'=>$emailmedecin]);
        $idmedecin=$medecinloggedIn[0]->getId();
        $creneau=$creneaurepo->findOneBy(['id'=>$id]);
        $listecreneauitem= $creneauitemrepo->findAll();
        if(isset($_POST['Modifier'])){
            if($request->isMethod('POST')){
                extract($_POST);
        $lecreneauitem = $creneauitemrepo->findOneBy(['id'=>$idlecreneau]);
        $creneau->setHeuredebut($heuredebut);
        $creneau->setHeurefin($heurefin);
        $creneau->setEtat(false);
        $creneau->setMedecin($medecinloggedIn[0]);
        $creneau->setCreneauitem($lecreneauitem);
        $em=$this->getDoctrine()->getManager();
        $em->persist($creneau);
        $em->flush();
        $this->addFlash('info', 'modifier avec succes.');
        return $this->redirectToRoute('ListeCReneau');
       
            }
    }
        return $this->render('medecin/editcreneau.html.twig', [
            'medecinloggedIn'=>$medecinloggedIn,
            'listecreneauitem'=>$listecreneauitem,
            'creneau'=>$creneau
        ]);
}
/**
     * @Route("/ListedemandeRV", name="ListedemandeRV")
     */
    public function getAlldemandeRV(MedecinRepository $medecinrepo,PriseDeRendezvousRepository $rvrepo,Request $request) {
        $usermedecin= $this->getUser();
        $emailmedecin=$usermedecin->getEmail();
        $medecinloggedIn=$medecinrepo->findBy(['Email'=>$emailmedecin]);
        $idmedecin=$medecinloggedIn[0]->getId();

        $listedemanderv=$rvrepo->findBy(['medecin'=>$idmedecin,'etat'=>false]);
        
        return $this->render('medecin/listedemanderv.html.twig', [
            'listerendezvous'=>$listedemanderv,
            'medecinloggedIn'=>$medecinloggedIn
        ]);
    }
/**
     * @Route("/ListeRVvalider", name="ListeRVvalider")
     */
    public function getAllvalideRV(MedecinRepository $medecinrepo,PriseDeRendezvousRepository $rvrepo,Request $request) {
        $usermedecin= $this->getUser();
        $emailmedecin=$usermedecin->getEmail();
        $medecinloggedIn=$medecinrepo->findBy(['Email'=>$emailmedecin]);
        $idmedecin=$medecinloggedIn[0]->getId();

        $listevaliderv=$rvrepo->findBy(['medecin'=>$idmedecin,'etat'=>true]);
        
        return $this->render('medecin/listervvalider.html.twig', [
            'listervvalider'=>$listevaliderv,
            'medecinloggedIn'=>$medecinloggedIn
        ]);
    }

    /**
     * @Route("/validerrdv/{id}", name="validerrdv")
    */
    public function validerrdv($id,PriseDeRendezvousRepository $rdvrepo,Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $rdv= $rdvrepo->findOneBy(['id'=>$id]);
        $rdv->setEtat(true);
        $em->persist($rdv);
        $em->flush();
                $this->addFlash('info', 'Rendez-vous validé avec success  validé avec succes.');
        return $this->redirectToRoute('ListeRVvalider');
    }

}

HelloDocteur/templates/medecin/addcreneau.html.twig
{% extends 'layoutmedecin.html.twig' %}
{% block content %}
    <div class="container">
        <h1>Ajouter Creneau</h1>
        <br><br>
        {% block flash %}
            {% for flash_message in app.session.flashbag.get('success') %}
                <div class="container alert alert-success" role="alert">
                    {{ flash_message }}
                </div>
            {% endfor %}
            {% for flash_message in app.session.flashbag.get('info') %}
                <div class="container alert alert-info" role="alert">
                    {{ flash_message }}
                </div>
            {% endfor %}
            {% for flash_message in app.session.flashbag.get('warning') %}
                <div class="container alert alert-warning" role="alert">
                    {{ flash_message }}
                </div>
            {% endfor %}
            {% for flash_message in app.session.flashbag.get('danger') %}
                <div class="container alert alert-danger" role="alert">
                    {{ flash_message }}
                </div>

            {% endfor %}
        {% endblock %}

        <form class="row" method="post">
            <div class="col-md-12 col-lg-8 col-lg-offset-2">
                <input type="text" id="inputStandard" name="heuredebut" class="form-control" placeholder="Entrer l'heure de debut">
            </div>
            <br><br>
            <br>
            <div class="col-md-12 col-lg-8 col-lg-offset-2">
                <input type="text" id="inputStandard" name="heurefin" class="form-control" placeholder="Entrer l'heure de fin">
            </div>
            <br><br>
            <br>

            <div class="col-md-12 col-lg-8 col-lg-offset-2">
                <select class="form-control" name="un">
                    <option value="">Date creneau</option>
                    {% for creneauitem in listecreneauitem %}

                        <option value="{{creneauitem.id}}">{{creneauitem.datecreneau | date}}</option>
                    {% endfor %}

                </select>

            </div><br><br><br>
            <div class="col-md-12 col-lg-8 col-lg-offset-4">
                <br><input type="submit" class="col-lg-6 btn medilife-btn btn-primary" value="Ajouter" name="AJouter">
            </div>
        </form>
    </div>
{% endblock %}

HelloDocteur/templates/medecin/editcreneau.html.twig
{% extends 'layoutmedecin.html.twig' %}
{% block content %}
    <div class="container">
        <h1>Ajouter Creneau</h1>
        <br><br>
        {% block flash %}
            {% for flash_message in app.session.flashbag.get('success') %}
                <div class="container alert alert-success" role="alert">
                    {{ flash_message }}
                </div>
            {% endfor %}
            {% for flash_message in app.session.flashbag.get('info') %}
                <div class="container alert alert-info" role="alert">
                    {{ flash_message }}
                </div>
            {% endfor %}
            {% for flash_message in app.session.flashbag.get('warning') %}
                <div class="container alert alert-warning" role="alert">
                    {{ flash_message }}
                </div>
            {% endfor %}
            {% for flash_message in app.session.flashbag.get('danger') %}
                <div class="container alert alert-danger" role="alert">
                    {{ flash_message }}
                </div>

            {% endfor %}
        {% endblock %}

        <form class="row" method="post">
            <div class="col-md-12 col-lg-8 col-lg-offset-2">
                <input type="text" value="{{creneau.heuredebut}}" id="inputStandard" name="heuredebut" class="form-control" placeholder="Entrer l'heure de debut">
            </div>
            <br><br>
            <br>
            <div class="col-md-12 col-lg-8 col-lg-offset-2">
                <input type="text" value="{{creneau.heurefin}}" id="inputStandard" name="heurefin" class="form-control" placeholder="Entrer l'heure de fin">
            </div>
            <br><br>
            <br>
            <div class="col-md-12 col-lg-8 col-lg-offset-2">
                <select class="form-control" name="idlecreneau" >
                    <option value="{{creneau.creneauitem.id}}">{{creneau.creneauitem.datecreneau | date('d-m-Y')}}</option>
                    {% for creneauitem in listecreneauitem %}
                        <option value="{{creneauitem.id}}">{{creneauitem.datecreneau | date}}</option>
                    {% endfor %}
                </select>
            </div><br><br><br>
            <div class="col-md-12 col-lg-8 col-lg-offset-4">
                <br><input type="submit" class="col-lg-6 btn medilife-btn btn-primary" value="Modifier" name="Modifier">
            </div>
        </form>
    </div>
{% endblock %}

HelloDocteur/templates/medecin/index.html.twig
{% extends 'layoutmedecin.html.twig' %}

HelloDocteur/templates/medecin/listecreneau.html.twig
{% extends 'layoutmedecin.html.twig' %}


    {% block content %}
    <div>
   {% block flash %}
            {% for flash_message in app.session.flashbag.get('success') %}
                <div class="container alert alert-success" role="alert">
                    {{ flash_message }}
                </div>
            {% endfor %}
            {% for flash_message in app.session.flashbag.get('info') %}
                <div class="container alert alert-info" role="alert">
                    {{ flash_message }}
                </div>
            {% endfor %}
            {% for flash_message in app.session.flashbag.get('warning') %}
                <div class="container alert alert-warning" role="alert">
                    {{ flash_message }}
                </div>
            {% endfor %}
            {% for flash_message in app.session.flashbag.get('danger') %}
                <div class="container alert alert-danger" role="alert">
                    {{ flash_message }}
                </div>
                
            {% endfor %}
        {% endblock %}

  <table class="table table-striped table-hover" id="datatable3" cellspacing="0" width="100%">
                    <thead>
<tr>


<th>Creneau</th>
<th>Date creneau</th>
<th>Etat</th>
<th>Actions</th>

</tr>
</thead><tbody>

{% for crene in creneau %}
<tr>
<td>{{ crene.heuredebut }}-{{ crene.heurefin }}</td>
<td>{{ crene.creneauitem.datecreneau | date }}</td>
<td>{{ crene.etat ? 'Validé' : 'Non Validé' }}</td>

<td>
<a href="{{ path('creneauedit', {'id' : crene.id }) }}" class="btn btn-rounded btn-primary btn-small">Editer</a>

</td>
</tr>
{% endfor %}
</tbody> 



</table>
  </div>
{% endblock %}

HelloDocteur/templates/medecin/listedemanderv.html.twig
{% extends 'layoutmedecin.html.twig' %}



    {% block content %}
    <div>
   {% block flash %}
            {% for flash_message in app.session.flashbag.get('success') %}
                <div class="container alert alert-success" role="alert">
                    {{ flash_message }}
                </div>
            {% endfor %}
            {% for flash_message in app.session.flashbag.get('info') %}
                <div class="container alert alert-info" role="alert">
                    {{ flash_message }}
                </div>
            {% endfor %}
            {% for flash_message in app.session.flashbag.get('warning') %}
                <div class="container alert alert-warning" role="alert">
                    {{ flash_message }}
                </div>
            {% endfor %}
            {% for flash_message in app.session.flashbag.get('danger') %}
                <div class="container alert alert-danger" role="alert">
                    {{ flash_message }}
                </div>
                
            {% endfor %}
        {% endblock %}

  <table class="table table-striped table-hover" id="datatable3" cellspacing="0" width="100%">
                    <thead>
<tr>

<th>nomcomplet</th>
<th>Telephone</th>
<th>adresse</th>
<th>date</th>
<th>heure</th>
<th>etat</th>
<th>Actions</th>


</tr>
</thead><tbody>

{% for prise in listerendezvous %}
<tr>
<td>{{ prise.patient.nomcomplet }}</td>
<td>{{ prise.patient.tel }}</td>
<td>{{ prise.patient.adresse }}</td>
<td>{{ prise.creneau.creneauitem.datecreneau | date }}</td> 
<td>{{ prise.creneau.heuredebut }} -{{ prise.creneau.heurefin }}</td>
<td>{{ prise.etat ? 'Validé' : 'Non Validé' }}</td>

<td>
                             <a href="{{ path('validerrdv', {'id' : prise.id }) }}" class="btn btn-rounded btn-primary btn-small">Valider</a>

</td>
</tr>
{% endfor %}
</tbody> 



</table>
  </div>
{% endblock %}

HelloDocteur/templates/medecin/listervvalider.html.twig
{% extends 'layoutmedecin.html.twig' %}



    {% block content %}
    <div>
   {% block flash %}
            {% for flash_message in app.session.flashbag.get('success') %}
                <div class="container alert alert-success" role="alert">
                    {{ flash_message }}
                </div>
            {% endfor %}
            {% for flash_message in app.session.flashbag.get('info') %}
                <div class="container alert alert-info" role="alert">
                    {{ flash_message }}
                </div>
            {% endfor %}
            {% for flash_message in app.session.flashbag.get('warning') %}
                <div class="container alert alert-warning" role="alert">
                    {{ flash_message }}
                </div>
            {% endfor %}
            {% for flash_message in app.session.flashbag.get('danger') %}
                <div class="container alert alert-danger" role="alert">
                    {{ flash_message }}
                </div>
                
            {% endfor %}
        {% endblock %}

  <table class="table table-striped table-hover" id="datatable3" cellspacing="0" width="100%">
                    <thead>
<tr>

<th>nomcomplet</th>
<th>Telephone</th>
<th>adresse</th>
<th>date</th>
<th>heure</th>

</tr>
</thead><tbody>

{% for prise in listervvalider %}
<tr>
<td>{{ prise.patient.nomcomplet }}</td>
<td>{{ prise.patient.tel }}</td>
<td>{{ prise.patient.adresse }}</td>
<td>{{ prise.creneau.creneauitem.datecreneau | date }}</td> 
<td>{{ prise.creneau.heuredebut }} -{{ prise.creneau.heurefin }}</td>

<td>
</td>
</tr>
{% endfor %}
</tbody> 



</table>
  </div>
{% endblock %}