HelloDocteur/src/Entity/Had.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\HadRepository")
 */
class Had
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Adresse;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $Tel;
    /**
    * @ORM\Column(type="string", length=250)
    */
   private $motif;

    
     /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Patient")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Patient;
 /**
     * @ORM\Column(type="boolean")
     */
    private $etat;

    /**
     * @ORM\Column(type="datetime")
     */
    private $datedemande;
     
    public function getId()
    {
        return $this->id;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->Tel;
    }

    public function setTel(string $Tel): self
    {
        $this->Tel = $Tel;

        return $this;
    }

    public function getFichemaladie()
    {
        return $this->Fichemaladie;
    }

    public function setFichemaladie($Fichemaladie): self
    {
        $this->Fichemaladie = $Fichemaladie;

        return $this;
    }

    /**
     * Get the value of Patient
     */ 
    public function getPatient()
    {
        return $this->Patient;
    }

    /**
     * Set the value of Patient
     *
     * @return  self
     */ 
    public function setPatient($Patient)
    {
        $this->Patient = $Patient;

        return $this;
    }

   /**
    * Get the value of motif
    */ 
   public function getMotif()
   {
      return $this->motif;
   }

   /**
    * Set the value of motif
    *
    * @return  self
    */ 
   public function setMotif($motif)
   {
      $this->motif = $motif;

      return $this;
   }

    /**
     * Get the value of etat
     */ 
    public function getEtat()
    {
        return $this->etat;
    }

    /**
     * Set the value of etat
     *
     * @return  self
     */ 
    public function setEtat($etat)
    {
        $this->etat = $etat;

        return $this;
    }

    public function getDatedemande(): ?\DateTimeInterface
    {
        return $this->datedemande;
    }

    public function setDatedemande(\DateTimeInterface $datedemande): self
    {
        $this->datedemande = $datedemande;

        return $this;
    }
}

HelloDocteur/src/Entity/Medecin.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
/**
 * @ORM\Entity(repositoryClass="App\Repository\MedecinRepository")
 */
class Medecin
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $Matricule;

   /**
     * @ORM\Column(type="string", length=90, unique=false)
     * @Assert\NotBlank()
     */
    private $nomcomplet;
    
    /**
     * @ORM\Column(type="string", length=30)
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $Tel;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $Adresse;

    /**
     * @ORM\Column(type="float",nullable=true)
     */
    private $Latitude;

    /**
     * @ORM\Column(type="float",nullable=true)
     */
    private $Longitude;
     /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Quartier")
     * @ORM\JoinColumn(nullable=true)
     */
    private $Quartier;
     /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Specialite")
     * @ORM\JoinColumn(nullable=true)
     */
    private $Specialite;


     /**
     * @ORM\OneToMany(targetEntity="App\Entity\Structure",mappedBy="medecins")
     * @ORM\JoinColumn(nullable=true)
     */
    private $structure;
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Creneau",mappedBy="medecin")
     * @ORM\JoinColumn(nullable=true)
     */
    private $creneau;
    /**
     * 
     * @ORM\Column(type="blob",nullable=true)
     */

    private $image;

    public function getId()
    {
        return $this->id;
    }

    public function getMatricule(): ?string
    {
        return $this->Matricule;
    }

    public function setMatricule(string $Matricule): self
    {
        $this->Matricule = $Matricule;

        return $this;
    }

  

    
    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->Tel;
    }

    public function setTel(string $Tel): self
    {
        $this->Tel = $Tel;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->Latitude;
    }

    public function setLatitude(float $Latitude): self
    {
        $this->Latitude = $Latitude;

        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->Longitude;
    }

    public function setLongitude(float $Longitude): self
    {
        $this->Longitude = $Longitude;

        return $this;
    }

    /**
     * Get the value of Quartier
     */ 
    public function getQuartier()
    {
        return $this->Quartier;
    }

    /**
     * Set the value of Quartier
     *
     * @return  self
     */ 
    public function setQuartier($Quartier)
    {
        $this->Quartier = $Quartier;

        return $this;
    }

    /**
     * Get the value of Specialite
     */ 
    public function getSpecialite()
    {
        return $this->Specialite;
    }

    /**
     * Set the value of Specialite
     *
     * @return  self
     */ 
    public function setSpecialite($Specialite)
    {
        $this->Specialite = $Specialite;

        return $this;
    }

    
    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image): self
    {
        $this->image = $image;

        return $this;
    }

    

    /**
     * Get the value of structure
     */ 
    public function getStructure()
    {
        return $this->structure;
    }

    /**
     * Set the value of structure
     *
     * @return  self
     */ 
    public function setStructure($structure)
    {
        $this->structure = $structure;

        return $this;
    }

    /**
     * Get the value of nomcomplet
     */ 
    public function getNomcomplet()
    {
        return $this->nomcomplet;
    }

    /**
     * Set the value of nomcomplet
     *
     * @return  self
     */ 
    public function setNomcomplet($nomcomplet)
    {
        $this->nomcomplet = $nomcomplet;

        return $this;
    }


    /**
     * Get the value of creneau
     */ 
    public function getCreneau()
    {
        return $this->creneau;
    }

    /**
     * Set the value of creneau
     *
     * @return  self
     */ 
    public function setCreneau($creneau)
    {
        $this->creneau = $creneau;

        return $this;
    }
}

HelloDocteur/src/Entity/Quartier.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\QuartierRepository")
 */
class Quartier
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $libelle;
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Region")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Region;


    public function getId()
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    /**
     * Get the value of Region
     */ 
    public function getRegion()
    {
        return $this->Region;
    }

    /**
     * Set the value of Region
     *
     * @return  self
     */ 
    public function setRegion($Region)
    {
        $this->Region = $Region;

        return $this;
    }
}

HelloDocteur/src/Entity/Region.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RegionRepository")
 */
class Region
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $libelle;
     /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Pays")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Pays;


    public function getId()
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    /**
     * Get the value of Pays
     */ 
    public function getPays()
    {
        return $this->Pays;
    }

    /**
     * Set the value of Pays
     *
     * @return  self
     */ 
    public function setPays($Pays)
    {
        $this->Pays = $Pays;

        return $this;
    }
}

HelloDocteur/src/Controller/AccueilController.php
<?php

namespace App\Controller;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use App\Entity\Specialite;
use App\Entity\Newsletter;
use App\Repository\SpecialiteRepository;
use App\Repository\QuartierRepository;
use App\Repository\RegionRepository;
use App\Repository\MedecinRepository;
use App\Repository\StructureRepository;
use Symfony\Component\HttpFoundation\Request;

class AccueilController extends Controller
{
    /**
     * @Route("/accueil", name="accueil")
     */
    public function index()
    {
        $user=$this->getUser();
        return $this->render('accueil/layoutaccueil.html.twig', [
            'controller_name' => 'AccueilController',
            'user'=>$user
        ]);
    }
    
        /**
         * @Route("/contact", name="contact")
         */
        public function contact()
        {
        $user=$this->getUser();

            return $this->render('accueil/contact.html.twig', [
                'controller_name' => 'AccueilController',
            'user'=>$user

            ]);
        }
          /**
         * @Route("/search", name="search")
         */
        public function search(Request $request,MedecinRepository $medecinrepo,StructureRepository $structurerepo,SpecialiteRepository $specialiterepo,RegionRepository $regionrepo)
        {
        $user=$this->getUser();

            setlocale(LC_TIME, 'fr_FR.UTF8', 'fr.UTF8', 'fr_FR.UTF-8', 'fr.UTF-8');
            $em = $this->getDoctrine()->getManager();
            $precedent=0;
            $suivant=4;
            $medecins=$medecinrepo->findAll();
            
           
            if(isset($_POST['Sinscrire'])){
                if($request->isMethod('POST')) {
                     extract($_POST);
                     $newsletter = new  Newsletter();
                     $newsletter->setEmail($newsletterEmail);
                     $em->persist($newsletter);
                     $em->flush();
                     $this->addFlash('success', 'Votre demande a bien été enregistré.');

                 }
            }

            if(isset($_POST['Rechercher'])){
                extract($_POST);
                if($request->isMethod('POST')){
                    if($specialite==null && $lieu==null ){
                        $medecins=$medecinrepo->findAll();
                    }
                     else if($specialite==null){
                        $medecins=$medecinrepo->findByRegion($lieu);
                    }
                   else if($lieu==null){
                        
                        $medecins=$medecinrepo->findBySpecialite($specialite);
                        
                    }
                    else{
                        $medecins=$medecinrepo->findBySpecialiteAndRegion($specialite,$lieu);
                    }

                }

            }
            
            foreach ($medecins as $values) {
                $values->setCreneau($this->get('knp_paginator')->paginate(
                    $values->getCreneau(),
                    $request->query->get('page', 1)/*le numéro de la page à afficher*/,
                      4/*nbre d'éléments par page*/
                ));
                $values->setImage(base64_encode(stream_get_contents($values->getImage())));

            }
           
            $structureslist=$structurerepo->findAll();
            $structures = $this->get('knp_paginator')->paginate(
                $structureslist,
                $request->query->get('page', 1)/*le numéro de la page à afficher*/,
                  10/*nbre d'éléments par page*/
            );
            $em = $this->getDoctrine()->getManager();
            $specialites=$specialiterepo->findAll();
            $regions=$regionrepo->findAll();

            return $this->render('accueil/search.html.twig', [
                'medecins' => $medecins,
                'structures' => $structures,
                'specialites'=>$specialites,
                'regions'=>$regions,
            'user'=>$user

                
            ]);
        }
        
        /**
     * @Route("/accueil", name="accueil")
     */
    public function specialite(MedecinRepository $medecinrepo,Request $request,SpecialiteRepository $specialiterepo,RegionRepository $regionrepo)
    {
        $user=$this->getUser();

    
    $em = $this->getDoctrine()->getManager();
    $specialites=$specialiterepo->findAll();
    $regions=$regionrepo->findAll();


    return $this->render('accueil/layoutaccueil.html.twig', [
        'specialites'=>$specialites,
        'regions'=>$regions,
        'user'=>$user

    ]);
    }
      /**
     * @Route("/detailMedecin/{id}", name="detailMedecin")
     */
    public function detailmedecin(Request $request,$id,SpecialiteRepository $specialiterepo,RegionRepository $regionrepo,MedecinRepository $medecinrepo)
    {

        $user=$this->getUser();
    
    $em = $this->getDoctrine()->getManager();
    $specialites=$specialiterepo->findAll();
    $regions=$regionrepo->findAll();
    $medecinBYId=$medecinrepo->findOneBy(['id'=>$id]);
    foreach($medecinBYId as $values){
        $values->setImage(base64_encode(stream_get_contents($values->getImage())));
    
}
    return $this->render('accueil/detailmedcin.html.twig', [
        'specialites'=>$specialites,
        'regions'=>$regions,
        'medecin'=>$medecinBYId,
        'user'=>$user
        
    ]);
    }
    /**
     * @Route("/detailstructure/{id}", name="detailstructure")
     */
    public function detailstructure(Request $request,$id,StructureRepository $structurerepo)
    {    $user=$this->getUser();

        $em = $this->getDoctrine()->getManager();
        $structures=$structurerepo->findOneBy(['id'=>$id]);

        return $this->render('accueil/detailstructure.html.twig', [
        'structures'=>$structures,  
        'user'=>$user

    ]);
    }
    /** 
   * @Route("/precedent") 
*/ 
public function precedentAction(Request $request) {  
  
    if ($request->isXmlHttpRequest()) {  
       $precedent=0;  
      
       return $precedent; 
    } else { 
       return $this->render('accueil/search.html.twig'); 
    } 
 }     
    
}
    

HelloDocteur/templates/accueil/contact.html.twig
{% extends 'base.html.twig' %}
{% block body %}

 </header>
    <!-- ***** Header Area End ***** -->

    <!-- ***** Breadcumb Area Start ***** -->
    <section class="breadcumb-area bg-img gradient-background-overlay" style="background-image: url(img/bg-img/breadcumb3.jpg);">
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <div class="col-12">
                    <div class="breadcumb-content">
                        <h3 class="breadcumb-title">Contact</h3>
                        <p>Lorem ipsum dolor sit amet, consectetuer</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ***** Breadcumb Area End ***** -->

    <section class="medilife-contact-area section-padding-100">
        <div class="container">
            <div class="row">
                <!-- Contact Form Area -->
                <div class="col-12 col-lg-8">
                    <div class="contact-form">
                        <h5 class="mb-50">Get in touch</h5>

                        <form action="#" method="post">
                            <div class="form-group">
                                <input type="text" class="form-control" id="contact-name" placeholder="Name">
                            </div>
                            <div class="form-group">
                                <input type="email" class="form-control" id="contact-email" placeholder="Email">
                            </div>
                            <div class="form-group">
                                <textarea class="form-control" name="message" id="message" cols="30" rows="10" placeholder="Message"></textarea>
                            </div>
                            <button type="submit" class="btn medilife-btn">Send Message <span>+</span></button>
                        </form>
                    </div>
                </div>

                <div class="col-12 col-lg-4">
                    <div class="content-sidebar">


                        <!-- Contact Card -->
                        <div class="medilife-contact-card mb-50">

                            <div class="single-contact d-flex align-items-center">
                                <div class="contact-icon mr-30">
                                    <i class="icon-doctor"></i>
                                </div>
                                <div class="contact-meta">
                                    <p>Address: sacre coeur 3 <br>dakar, senegal</p>
                                </div>
                            </div>

                            <div class="single-contact d-flex align-items-center">
                                <div class="contact-icon mr-30">
                                    <i class="icon-doctor"></i>
                                </div>
                                <div class="contact-meta">
                                    <p>Phone: +221 77 268 89 33</p>
                                </div>
                            </div>

                            <div class="single-contact d-flex align-items-center">
                                <div class="contact-icon mr-30">
                                    <i class="icon-doctor"></i>
                                </div>
                                <div class="contact-meta">
                                    <p>Email: hello.doctorsn@gmail.com</p>
                                </div>
                            </div>


                            <div class="contact-social-area">
                                <a href="#"><i class="fa fa-google-plus"></i></a>
                                <a href="#"><i class="fa fa-pinterest"></i></a>
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                            </div>

                        </div>
                        

                        <!-- medilife Emergency Card -->
                        <div class="medilife-emergency-card bg-img bg-overlay" style="background-image: url(img/bg-img/about1.jpg);">
                            <i class="icon-smartphone"></i>
                            <h2>For Emergency calls</h2>
                            <h3>+12-823-611-8721</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Google Maps -->
    <div class="map-area mb-100">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div id="googleMap" class="googleMap"></div>
                </div>
            </div>
        </div>
    </div>

<!-- Google Maps -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAwuyLRa1uKNtbgx6xAJVmWy-zADgegA2s"></script>
    <script src="js/map-active.js"></script>



{% endblock %}

HelloDocteur/templates/accueil/detailmedcin.html.twig
{% extends 'base.html.twig' %}
{% block body %}
 <style>
 
        .header1 {
            height: 100px;
            background-color: rgb(97, 97, 102);
        }

        .header2 {
            height: 50px;
            background-color: rgb(224, 217, 204);
            margin-top: -20px;
            padding-top: 5px;

        }

        .nav {
            display: flex;
            list-style-type: none;
            width: 50%;
            margin: auto;
        }

        .lien {
            text-decoration: none;
            margin: 10px;
            color: black;
            font-weight: bold;
            font-size: 18px;
        }

        .lien:hover {
            border-bottom: 3px solid blue;
        }

        .logo {
            height: 100px;
            width: 100px;
            border-radius: 25px;
            padding: 10px;
            margin-left: 150px;
        }

        .section {
            width: 80%;
            margin: auto;
        }
        .specialite{
            padding: 10px;
            color: blue;
            background-color: white;
            border:2px solid #0000ff;
            width: auto;
            max-width: 300px;
            border-radius: 10px;
            margin: 10px;

        }
        .spec{
            display: flex;
            list-style-type: none;
        }
        .addresse{
            font-size: 18px;
            padding: 5px;
        }
        .horaires{
            list-style-type: none;

        }
        .card{
          margin-bottom:30px;
          padding:20px;
        }
    </style>

    <div class="container" style="padding-top:200px;">
        <header class="">
            <div class="header1" style="display:flex;">

                                    <img src="{{asset('img/img/medecin.jpg')}}" style="height:70px;width:70px;border-radius:50%;" class="col-lg-2" alt="" >
                <h3 class="col-lg-4" style="color:white;"><br>{{medecin.nomcomplet}}</h3>

            </div>
            <div class="header2">
                <ul class="nav">
                    <li><a class="lien" href="#presentation">Presentation</a></li>
                    <li><a class="lien" href="#carteetcoordonnees">Carte et Coordonnées</a></li>
                    <li><a class="lien" href="#horaires">Horaires</a></li>
                    <li><a class="lien" href="#tarif">Tarif</a></li>
                </ul>
            </div>
        </header>
        <section class="section">
            <div class="card" id="presentation">
                <h3>Présentation</h3>
                <p>
                    Le docteur Thierry Galtier est spécialiste de la chirurgie de l'oeil depuis plus de 20 ans. Il vous
                    accueille au sein de son cabinet de Bordeaux, situé au 14 rue Elisée Reclus. </p>
                    <hr>
                    <h3>Spécialités</h3>
                    <ul class="spec">
                        <li class="specialite">
{{medecin.specialite.libelle}}                        </li>   
                    </ul>
                    {% if medecin.structure  != null %}
                    <hr><h3>Structures</h3>
                    <ul class="spec">
                     {% for struc in medecin.structure %}
                        <li class="specialite">
          {{struc.libelle}}                        </li> 
                                    {% endfor %} 
                         
                    </ul>{% endif %}
                    <hr>
                </div>
            <div class="card" id="carteetcoordonnees">
                <h3>Carte et coordonéées</h3>
                <ul>
                        <li class="addresse"><strong>Pays:</strong> {{medecin.quartier.region.pays.libelle}} </li>
                        <li class="addresse"><strong>Region:</strong>{{medecin.quartier.region.libelle}} </li>
                        <li class="addresse"><strong>Quartier:</strong>{{medecin.quartier.libelle}} </li>
                        <li class="addresse"><strong>Adresse:</strong>{{medecin.adresse}} </li>
                        <li class="addresse"><strong>Téléphone:</strong>{{medecin.tel}} </li>
                </ul>
            </div>
            <div class="card" id="horaires">
                <h3>Horaires</h3>
                <p>Horaires et contacts <br>   
                                       Contact du secrétariat
                    04 66 23 32 21 </p>
                <ul class="horaires"><li>                    Ouverture du secrétariat
                </li>
                    <li>Lundi :
                        08h30 - 18h00</li><li>Mardi :
                            08h30 - 18h00</li><li>Mercredi :
                                08h30 - 18h00</li><li>jeudi :
                                    08h30 - 18h00</li><li>Vendredi :
                                        08h30 - 18h00</li>
                </ul>
               
            </div>
            <div class="card" id="tarif">
                <h3>Tarifs</h3>
 

           <ul>
               <li>
                Première consultation 
                3000 Fcfa<hr>
               </li>
               <li>Enfant - Première consultation 4000Fcfa<hr></li><li>Enfant - Consultation de suivi 3000Fcfa<hr></li>
           </ul> </div>
        </section>
    </div>
{% endblock %}

HelloDocteur/templates/accueil/detailstructure.html.twig
{% extends 'base.html.twig' %}
{% block body %}
 <style>
 
        .header1 {
            height: 100px;
            background-color: rgb(97, 97, 102);
        }

        .header2 {
            height: 50px;
            background-color: rgb(224, 217, 204);
            margin-top: -20px;
            padding-top: 5px;

        }

        .nav {
            display: flex;
            list-style-type: none;
            width: 50%;
            margin: auto;
        }

        .lien {
            text-decoration: none;
            margin: 10px;
            color: black;
            font-weight: bold;
            font-size: 18px;
        }

        .lien:hover {
            border-bottom: 3px solid blue;
        }

        .logo {
            height: 100px;
            width: 100px;
            border-radius: 25px;
            padding: 10px;
            margin-left: 150px;
        }

        .section {
            width: 80%;
            margin: auto;
        }
        .specialite{
            padding: 10px;
            color: blue;
            background-color: white;
            border:2px solid #0000ff;
            width: auto;
            max-width: 300px;
            border-radius: 10px;
            margin: 10px;

        }
        .spec{
            display: flex;
            list-style-type: none;
        }
        .addresse{
            font-size: 18px;
            padding: 5px;
        }
        .horaires{
            list-style-type: none;

        }
        .card{
          margin-bottom:30px;
          padding:20px;
        }
    </style>

    <div class="container" style="padding-top:200px;">
        <header class="">
            <div class="header1" style="display:flex;">

                                    <img src="{{asset('img/img/m.jpg')}}" style="height:70px;width:70px;border-radius:50%;" class="col-lg-2" alt="" >
                <h3 class="col-lg-4" style="color:white;"><br>{{structures.libelle}}</h3>

            </div>
            <div class="header2">
                <ul class="nav">
                    <li><a class="lien" href="#presentation">Presentation</a></li>
                    <li><a class="lien" href="#carteetcoordonnees">Carte et Coordonnées</a></li>
                    <li><a class="lien" href="#horaires">Horaires</a></li>
                    <li><a class="lien" href="#tarif">Tarif</a></li>
                </ul>
            </div>
        </header>
        <section class="section">
            <div class="card" id="presentation">
                <h3>Présentation</h3>
                <p>
                    Le docteur Thierry Galtier est spécialiste de la chirurgie de l'oeil depuis plus de 20 ans. Il vous
                    accueille au sein de son cabinet de Bordeaux, situé au 14 rue Elisée Reclus. </p>
                    <hr>
                    <h3>Spécialités</h3>
                    <ul class="spec">
                    {% for row in structures.specialite %}
                        <li class="specialite">
{{row.libelle}}</li>                                       {% endfor %}

                    </ul>
                    {% if structures.medecins !== null %}
                    <hr><h3>Medecins</h3>
                    <ul class="spec">
                     {% for struc in structures.medecins %}
                        <li class="specialite">
          {{struc.nomcomplet}}                        </li> 
                                    {% endfor %} 
                         
                    </ul>
                    <hr>
                    {% endif %}
                </div>
            <div class="card" id="carteetcoordonnees">
                <h3>Carte et coordonéées</h3>
                <ul>
                        <li class="addresse"><strong>Pays:</strong> {{structures.quartier.region.pays.libelle}} </li>
                        <li class="addresse"><strong>Region:</strong>{{structures.quartier.region.libelle}} </li>
                        <li class="addresse"><strong>Quartier:</strong>{{structures.quartier.libelle}} </li>
                        <li class="addresse"><strong>Adresse:</strong>{{structures.adresse}} </li>
                        <li class="addresse"><strong>Téléphone:</strong>{{structures.tel}} </li>
                </ul>
            </div>
            <div class="card" id="horaires">
                <h3>Horaires</h3>
                <p>Horaires et contacts <br>   
                                       Contact du secrétariat
                    04 66 23 32 21 </p>
                <ul class="horaires"><li>                    Ouverture du secrétariat
                </li>
                    <li>Lundi :
                        08h30 - 18h00</li><li>Mardi :
                            08h30 - 18h00</li><li>Mercredi :
                                08h30 - 18h00</li><li>jeudi :
                                    08h30 - 18h00</li><li>Vendredi :
                                        08h30 - 18h00</li>
                </ul>
               
            </div>
            <div class="card" id="tarif">
                <h3>Tarifs</h3>
 

           <ul>
               <li>
                Première consultation 
                3000 Fcfa<hr>
               </li>
               <li>Enfant - Première consultation 4000Fcfa<hr></li><li>Enfant - Consultation de suivi 3000Fcfa<hr></li>
           </ul> </div>
        </section>
    </div>
{% endblock %}